apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app
spec:
  selector:
    matchLabels:
      app: flask-test-app

  replicas: 4

  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
        - name: flask-test-app
          image: vishal7500/vishal4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
