apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app
spec:
  selector:
    matchLabels:
      app: flask-test-app
<<<<<<< HEAD
  replicas: 4
=======
  replicas: 2
>>>>>>> 563e2d77e2254d3302f009192c0a4d78ad13e7bb
  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
        - name: flask-test-app
          image: vishal7500/vishal4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
