apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app
spec:
  selector:
    matchLabels:
      app: flask-test-app
  replicas: 5
  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
        - name: flaskApp
          image: vishal7500/sader
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090